import type { Metadata } from 'next'
import './globals.css'
import Header from './src/shared/ui/Header'
import ReactQueryProvider from './providers/ReactQueryProvider'
import { WebSocketProvider } from './src/shared/contexts/WebSocketContext'
import AnimateNotification from './src/shared/ui/AnimateNotification'
import ClientAuthInit from './providers/ClientAuthInit'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className='font-wix bg-900 xl:px-20 md:px-8 px-10'>
				<ReactQueryProvider>
					<WebSocketProvider>
						<ClientAuthInit>
							<Header />
							{children}
						</ClientAuthInit>
						<AnimateNotification />
					</WebSocketProvider>
				</ReactQueryProvider>
			</body>
		</html>
	)
}
